# Generated by Django 3.1 on 2020-08-16 16:18

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', tinymce.models.HTMLField()),
                ('tid', models.IntegerField(default=-1)),
                ('message', models.CharField(default='', max_length=200)),
                ('isTeamarticle', models.BooleanField(default=False)),
                ('isAbandoned', models.BooleanField(default=False)),
                ('visibility', models.IntegerField(default=1)),
                ('commentGranted', models.BooleanField(default=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('lastedittime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('commentTime', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.article')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('creatorid', models.IntegerField()),
                ('membernumber', models.IntegerField(default=0)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('tname', models.CharField(max_length=100)),
                ('tIntro', models.CharField(max_length=200)),
                ('Teamphoto', models.ImageField(default='Tphoto/default.jpg', upload_to='Tphoto/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.DateField(default='2000-1-1')),
                ('password', models.CharField(default='a12345678', max_length=30)),
                ('tags', models.TextField(default='')),
                ('uphoto', models.ImageField(default='uphoto/default.jpg', upload_to='uphoto/')),
                ('createtime', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tocomment',
            fields=[
                ('tcid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('commentTime', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMessage',
            fields=[
                ('tmid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalMessage',
            fields=[
                ('pmid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500)),
                ('tid', models.IntegerField(default=-1)),
                ('aid', models.IntegerField(default=-1)),
                ('isInviteMessage', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='MemberShip',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('participateTime', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('favoriteTime', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.user'),
        ),
        migrations.CreateModel(
            name='BrowerHistory',
            fields=[
                ('BHid', models.AutoField(primary_key=True, serialize=False)),
                ('browertime', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.user'),
        ),
    ]
