# Generated by Django 3.1 on 2020-08-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalmessage',
            name='type',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
