# Generated by Django 2.2.3 on 2020-08-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalmessage',
            name='type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
