# Generated by Django 2.2.3 on 2020-08-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalmessage',
            name='aid',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='personalmessage',
            name='isInviteMessage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personalmessage',
            name='tid',
            field=models.IntegerField(default=-1),
        ),
    ]
